site_name: histo-omics-lite
site_description: Lightweight histology×omics alignment with a tiny, CPU-only pipeline
site_url: https://altalanta.github.io/histo-omics-lite
repo_url: https://github.com/altalanta/histo-omics-lite
repo_name: altalanta/histo-omics-lite

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            docstring_style: google

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Concepts: concepts.md
  - Determinism: determinism.md
  - API Reference: api.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/altalanta/histo-omics-lite
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/histo-omics-lite

copyright: Copyright &copy; 2024 Altalanta