# Base evaluation configuration
defaults:
  - /data: synthetic
  - _self_

# Paths
checkpoint_path: null  # Must be provided via CLI
output_dir: "${oc.env:OUTPUT_DIR,outputs/eval}"

# Evaluation parameters
metrics:
  retrieval:
    k_values: [1, 5, 10]
    metrics: ["precision", "recall", "map"]
  
  classification:
    metrics: ["auroc", "auprc", "f1", "accuracy"]
    
  calibration:
    metrics: ["ece", "mce", "brier_score"]
    bins: 15

# Confidence intervals
confidence_intervals:
  enabled: true
  method: "bootstrap"
  n_bootstrap: 1000
  confidence_level: 0.95
  seed: 42

# Data parameters
data:
  batch_size: 64
  num_workers: 4
  pin_memory: true

# Device configuration
device: "auto"  # auto, cpu, cuda

# Reproducibility
seed: 42
deterministic: true