# Fast debug configuration - CPU only, 1 epoch
# defaults:
#   - base_config

seed: 42
temperature: 0.07
omics_input_dim: 50
output_dir: artifacts

data:
  root: data/synthetic
  batch_size: 16
  num_workers: 0
  val_fraction: 0.25
  use_webdataset: false

optimizer:
  lr: 0.001
  weight_decay: 0.0

trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1
  limit_train_batches: null
  limit_val_batches: null
  check_val_every_n_epoch: 1
  deterministic: true
