# defaults:
#   - base_config

seed: 42
temperature: 0.07
omics_input_dim: 50
output_dir: artifacts

data:
  root: data/synthetic
  batch_size: 64
  num_workers: 4
  val_fraction: 0.25
  use_webdataset: false

optimizer:
  lr: 0.002
  weight_decay: 0.01

trainer:
  max_epochs: 5
  accelerator: auto  # Will use GPU if available
  devices: 1
  precision: 16-mixed  # Use mixed precision if GPU available
  limit_train_batches: null
  limit_val_batches: null
  check_val_every_n_epoch: 1