# Alignment network model configuration
_target_: histo_omics_lite.models.alignment_net.AlignmentNet

# Model architecture
histology_encoder:
  _target_: histo_omics_lite.models.encoders.HistologyEncoder
  backbone: "resnet18"
  pretrained: true
  feature_dim: 512
  dropout: 0.1
  pool_type: "adaptive_avg"

omics_encoder:
  _target_: histo_omics_lite.models.encoders.OmicsEncoder
  input_dim: 2000
  hidden_dims: [1024, 512, 256]
  feature_dim: 512
  dropout: 0.2
  activation: "relu"
  batch_norm: true

# Alignment head
alignment_head:
  _target_: histo_omics_lite.models.heads.AlignmentHead
  feature_dim: 512
  projection_dim: 128
  temperature: 0.07
  normalize: true

# Loss configuration
loss:
  _target_: histo_omics_lite.losses.contrastive.InfoNCELoss
  temperature: 0.07
  reduction: "mean"
  
# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8

# Learning rate scheduler
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 100
  eta_min: 1e-6
  
# Model compilation
compile: false

# Metrics to track
metrics:
  - "top1_accuracy"
  - "top5_accuracy"
  - "contrastive_loss"
  - "embedding_similarity"